# Use a lightweight Python image
FROM python:3.11-slim

# Set workdir inside container
WORKDIR /app

# Install system dependencies (if needed)
RUN apt-get update && apt-get install -y build-essential

# Copy environment config files
COPY conda.yaml conda.yaml
COPY MLproject MLproject

# Copy source code
COPY src/ src/
COPY data/ data/

# Install Python dependencies directly (not using Conda for simplicity)
RUN pip install --upgrade pip && \
    pip install mlflow scikit-learn pandas fastapi uvicorn

# Optional: install any extra packages here if needed
# RUN pip install psycopg2-binary ...

# Expose port for FastAPI server
EXPOSE 8000

# Command to run FastAPI server (serves your trained model)
CMD ["uvicorn", "src.serve:app", "--host", "0.0.0.0", "--port", "8000"]
